services:
  - type: web
    name: afnjp-ranking-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_CHANNEL_ID
        value: "1462739286620373024"
